
%include "PulWaveform.i"
%include "PulComposite.i"
%include "Pulse.i"
%include "PulGauss.i"
%include "PulSinc.i"
%include "PulCycle.i"
%include "PulMLEV.i"
%include "PulTrain.i"
%include "PulSupCycle.i"
%include "PulCHIRP.i"
%include "PulGARP.i"
%include "PulWALTZ.i"
%include "PulTrainSCyc.i"
%include "PulDANTE.i"
%include "PulAuxil.i"
